version: '3'

services:
  nginx:
    build:
      dockerfile: ./images/nginx/Dockerfile # путь до dockerFile из которого будет собран docker-образ
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    depends_on:
      - php-fpm
    volumes:
       - ./app:/var/www/app/
  php-fpm:
    build:
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
    networks:
      - network
    volumes:
      - ./app:/var/www/app/
      - ./images/php-fpm/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
  # mysql:
  #   image: "mariadb:10.3"
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MARIADB_ROOT_PASSWORD: passwd
  #     MYSQL_DATABASE: "db_name"
  #   networks:
  #     - network
  #   volumes:
  #     - ./:/var/www/app/
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - network

networks:
  network:
    driver: bridge