version: '3'

services:
  nginx:
    build:
      dockerfile: ./images/nginx/Dockerfile # путь до dockerFile из которого будет собран docker-образ
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - php-fpm
    volumes:
       - ./app:/var/www/app/
  php-fpm:
    build:
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
    networks:
      - network
    volumes:
      - ./app:/var/www/app/

networks:
  network:
    driver: bridge