version: '3'

services:
  nginx:
    build:
      dockerfile: ./images/nginx/Dockerfile # путь до dockerFile из которого будет собран docker-образ
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - php-fpm
    volumes:
       - ./app:/var/www/
  php-fpm:
    build:
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
    networks:
      - network
    volumes:
      - ./app:/var/www/
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./images/frontend/Dockerfile
    networks:
      - network
    volumes:
      - ./app:/var/www/
    ports:
      - "3000:3000"
    tty: true
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - network
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 5550:8080
    networks:
      - network

networks:
  network:
    driver: bridge
