version: '3'

services:
  nginx:
    build:
      dockerfile: ./images/nginx/Dockerfile # путь до dockerFile из которого будет собран docker-образ
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - php-fpm
    volumes:
       - ./app/backend:/var/www/backend/
       - ./app/frontend:/var/www/frontend/
  php-fpm:
    build:
      context: .
      dockerfile: ./images/php-fpm/Dockerfile
    networks:
      - network
    volumes:
      - ./app/backend:/var/www/backend/
  frontend:
    build:
      context: .
      dockerfile: ./images/frontend/Dockerfile
    networks:
      - network
    volumes:
      - ./app/frontend:/var/www/frontend/
    ports:
      - "3000:3000"


networks:
  # явно объявленные сети
  network:
    driver: bridge
